spring:
  config:
    activate:
      on-profile: prov
server:
  port: 8888
camel:
  springboot:
    routes-include-pattern: file:yaml/provAgent/**/*.yaml
# Logging
logging:
  level:
    root: info
    org.apache.kafka.clients.consumer.ConsumerConfig: warn
  logback:
    rollingpolicy:
      max-history: 90
  file:
    name: logs/mylog.log

