spring:
  config:
    activate:
      on-profile: prov
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.30.1.76:5432/dbdsp2
    username: devusdsp2
    password: devusdsp2
mybatis:
  config-location: classpath:/mybatis/mapper-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
server:
  port: 8888
camel:
  springboot:
    routes-include-pattern: file:yaml/provAgent/**/*.yaml
# Logging
logging:
  level:
    root: info
  #    org.apache.kafka.clients.consumer.ConsumerConfig: warn
  logback:
    rollingpolicy:
      max-history: 90
  file:
    name: logs/${spring.config.activate.on-profile}.log

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.30.1.76:5432/dbdsp2
    username: devusdsp2
    password: devusdsp2
mybatis:
  config-location: classpath:/mybatis/mapper-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
